$("#login-button-ClariantPRD").click(function(event){
	window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/fwicgukio4d5b53/manifest.plist")
});
$("#login-button-ClariantQA").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/6d6hr5fmwxmx3we/manifest.plist")
});
$("#login-button-Heritage").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/37qf8fmeuy50s6l/manifest.plist")
});
$("#login-button-mJC").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/5n9r0fiobugk2zs/manifest.plist")
});
$("#login-button-ODSmyAsset").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/8icyvz22u7kqu3l/manifest.plist")
});
$("#login-button-ODSmyAssetQA").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/cq1aalpdtcwfzew/manifest.plist")
});
$("#login-button-ODSmyForms").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/1c8j6s8j4mc0ie5/manifest.plist")
});
$("#login-button-ODSmyFormsES1").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/6tpudhxhololjvh/manifest.plist")
});
$("#login-button-ClariantmyForms").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/t7tpmncslswqibq/manifest.plist")
});
$("#login-button-mJCQA").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/rboiapvihif0623/manifest.plist")
});
$("#login-button-mJCSales").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/scl/fi/9hounfwg19hqnldqlmvhh/manifest.plist")
});
$("#login-button-ClariantmyFormsQA").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/jcoiirdacplmsu0/manifest.plist")
});

