$("#login-button-ClariantPRD").click(function(event){
	window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/fwicgukio4d5b53/manifest.plist")
});
$("#login-button-ClariantQA").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/6d6hr5fmwxmx3we/manifest.plist")
});
$("#login-button-Heritage").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/2lqo4uqw7h3n6lx/manifest.plist")
});
$("#login-button-mJC").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/q4xlqiargau307y/manifest.plist")
});
$("#login-button-ODSmyAsset").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/hrqelwvlft50xex/manifest.plist")
});
$("#login-button-ODSmyForms").click(function(event){
    window.open("itms-services://?action=download-manifest&url=https://dl.dropboxusercontent.com/s/1c8j6s8j4mc0ie5/manifest.plist")
});

